[package]
name = "ch7"
version = "0.0.1"
edition = "2021"
authors = ["scPointer <jax01@foxmail.com>"]

[dependencies]
virtio-drivers = { git = "https://github.com/rcore-os/virtio-drivers", rev = "4ee80e5" }
polyhal = {git = "https://github.com/xushanpu123/polyhal.git",features = ["kcontext", "trap", "boot"]}
xmas-elf = "0.8.0"
spin = "0.9"
log = "0.4"

linker = { git = "https://github.com/crates-rcore-in-single-workspace/linker.git" }
rcore-console = { git = "https://github.com/crates-rcore-in-single-workspace/console.git" }
# kernel-context = { git = "https://github.com/crates-rcore-in-single-workspace/kernel-context.git", features = ["foreign"] }
kernel-alloc = { git = "https://github.com/crates-rcore-in-single-workspace/kernel-alloc.git" }
kernel-vm = { git = "https://github.com/crates-rcore-in-single-workspace/kernel-vm.git" }
syscall = { git = "https://github.com/crates-rcore-in-single-workspace/syscall.git", features = ["kernel"] }
rcore-task-manage = { git = "https://github.com/crates-rcore-in-single-workspace/task-manage.git", features = ["proc"] }
easy-fs = { git = "https://github.com/crates-rcore-in-single-workspace/easy-fs.git" }
signal = { git = "https://github.com/crates-rcore-in-single-workspace/signal.git" }
signal-impl = { git = "https://github.com/crates-rcore-in-single-workspace/signal-impl.git" }

[build-dependencies]
linker = { git = "https://github.com/crates-rcore-in-single-workspace/linker.git" }
