[package]
name = "ch3"
version = "0.0.1"
edition = "2021"
authors = ["YdrMaster <ydrml@hotmail.com>"]

[dependencies]
# polyhal = { git = "https://github.com/Byte-OS/polyhal.git", features = ["kcontext", "trap", "boot"]}
polyhal = {git = "https://github.com/xushanpu123/polyhal.git",features = ["kcontext", "trap", "boot"]}
log = "0.4"
kernel-alloc = { git = "https://github.com/crates-rcore-in-single-workspace/kernel-alloc.git" }
# buddy_system_allocator = "0.6"
lazy_static = { version = "1.4.0", features = ["spin_no_std"] }
linker = { git = "https://github.com/crates-rcore-in-single-workspace/linker.git" }
rcore-console = { git = "https://github.com/crates-rcore-in-single-workspace/console.git" }
# kernel-context = { git = "https://github.com/crates-rcore-in-single-workspace/kernel-context.git" }
syscall = { git = "https://github.com/crates-rcore-in-single-workspace/syscall.git", features = ["kernel"] }

[build-dependencies]
linker = { git = "https://github.com/crates-rcore-in-single-workspace/linker.git" }

[features]
coop = []
