name: CI

on:
  push:
    branches: [ "v3" ]
  pull_request:
    branches: [ "v3" ]

env:
  CARGO_TERM_COLOR: always
  rust_toolchain: nightly-2023-12-01

jobs:

  make:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
    

      - name: Build syscall
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --package syscall
      - name: usertests
        run: |
         cp user/src/bin/usertests.rs user/src/bin/initproc.rs
         rustup component add llvm-tools-preview
         export PATH="$HOME/.rustup/toolchains/$(rustup show active-toolchain)/bin:$PATH"
         cargo install cargo-binutils --version 0.3.0
         pip install toml
         pip install python-liquid
         pip install termcolor
         sudo apt update && sudo apt install -y qemu-system-misc qemu-system-arm qemu-system-x86
         ./run.py --ch 8 --arch x86_64 --release  qemu
         ./run.py --ch 8 --arch loongarch64 --release  qemu
