name: CI

on:
  push:
    branches: [ "v3" ]
  pull_request:
    branches: [ "v3" ]

env:
  CARGO_TERM_COLOR: always
  rust_toolchain: nightly-2023-12-01

jobs:

  make:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
    

      - name: Build syscall
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --package syscall
      - name: usertests
        run: |
         rustup component add llvm-tools-preview
         export PATH="$HOME/.rustup/toolchains/$(rustup show active-toolchain)/bin:$PATH"
         cargo install cargo-binutils --version 0.3.0
         pip install toml
         pip install python-liquid
         pip install termcolor
         apt install -y qemu-system-misc
         ./run.py --ch 8 --arch riscv64 --release  qemu
         ./run.py --ch 8 --arch aarch64 --release  qemu
         ./run.py --ch 8 --arriscv64
